sudo: false
dist: xenial
language: python
python:
- '3.7'
env:
- TOX_ENV=flake8
- TOX_ENV=test
install:
- pip install tox python-coveralls pytest pytest-cov

branches:
  only:
  - master
  - /\d+\.\d+\.\d+/
script:
- tox -e $TOX_ENV
- pytest --cov=Taiwanese-serif-to-Unicode/
after_success:
  - coveralls